<a href="https://colab.research.google.com/github/realcommang/BigDataProcess/blob/main/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5/%EC%A4%91%EA%B0%84%EB%8C%80%EB%B9%84/%EB%AA%A8%EB%B2%94%EB%8B%B5%EC%95%88/%EC%8B%A4%EC%8A%B51%EB%AA%A8%EB%B2%94%EB%8B%B5%EC%95%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#난수 발생기의 시드를 0으로 설정하여 재현성을 보장
np.random.seed(0)

#1에서 99 사이의 난수로 2*8 배열을 생성한다
A = np.random.randint(1, 99, size=(2,8))
A = np.array(A)

#배열의 모양(shape)과 내용을 출력한다
print(A.shape)
print(A.shape[0]) #2
print(A.shape[1]) #8
print(A)

#각 행에서 가장 큰 값을 찾아 출력
allMax = 0
subMax = [0,0]
for i in range(A.shape[0]):
  subMax[i] = 0
  for j in range(A.shape[1]):
    if subMax[i] < A[i][j]:
      subMax[i] = A[i][j]

  if allMax < subMax[i]:
    allMax = subMax[i]

print("All Max: " + str(allMax))
print("SubMax 0: " + str(subMax[0]))
print("SubMax 1: " + str(subMax[1]))

#배열을 2*2*4 모양으로 재구조화하고 모양과 내용 출력
B = A.reshape(2,2,4)
print(B.shape)
print(B)

C = B.copy()
#B 배열의 각 차원에서 처음 두 열을 슬라이싱하여 tmp1에 할당
tmp1 = B[:, :, :2]
#B 배열의 각 차원에서 세 번째 열부터 끝까지 슬라이싱하여 tmp2에 할당
tmp2 = B[:, :, 2:]

#C 배열의 각 차원에서 세 번째 열부터 끝까지를 tmp1의 값으로 대체
C[:, :, 2:] = tmp1
#C 배열의 각 차원에서 처음 두 열을 tmp2의 값으로 대체
C[:, :, :2] = tmp2
print(C)

(2, 8)
2
8
[[45 48 65 68 68 10 84 22]
 [37 88 71 89 89 13 59 66]]
All Max: 89
SubMax 0: 84
SubMax 1: 89
(2, 2, 4)
[[[45 48 65 68]
  [68 10 84 22]]

 [[37 88 71 89]
  [89 13 59 66]]]
[[[65 68 45 48]
  [84 22 68 10]]

 [[71 89 37 88]
  [59 66 89 13]]]
